'''
389. Find the Difference

You are given two strings s and t.

String t is generated by randomly shuffling string s and adding one extra letter.

Return the letter that was added.

Example 1:
    Input:
        s = "abcd"
        t = "abcde"

    Output:
        "e"

Example 2:
    Input:
        s = ""
        t = "y"

    Output:
        "y"

Constraints:
    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.
'''

# Bit Manipulation (XOR)

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        xor_result = 0

        for character in s:
            xor_result ^= ord(character)

        for character in t:
            xor_result ^= ord(character)

        return chr(xor_result)


# Example usage
solution = Solution()

# Example 1
s1 = "abcd"
t1 = "abcde"
print(solution.findTheDifference(s1, t1))
# Output: "e"

# Example 2
s2 = ""
t2 = "y"
print(solution.findTheDifference(s2, t2))
# Output: "y"

# Example 3
s3 = "aabbcc"
t3 = "abcbcad"
print(solution.findTheDifference(s3, t3))
# Output: "d"

# Example 4
s4 = "xyz"
t4 = "zxyw"
print(solution.findTheDifference(s4, t4))
# Output: "w"

# Example 5
s5 = "leetcode"
t5 = "leetcodea"
print(solution.findTheDifference(s5, t5))
# Output: "a"

# Example 6
s6 = "hello"
t6 = "ohllelx"
print(solution.findTheDifference(s6, t6))
# Output: "x"
